name: FWEntities
api: 4.0.0
version: 1.1
main: fwentities\Main
author: Varion

commands:
 fwentity:
  description: FWEntity Main Command

permissions:
  fwentities.use:
    description: "FWEntity Main Command"
    default: op  